name: Rust

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  release:
    release:
      types: [ published ]

env:
  CARGO_TERM_COLOR: always

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-20.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-46
      options: --privileged
    steps:
      - uses: actions/checkout@v2
      - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
        with:
          bundle: epic_asset_manager.flatpak
          manifest-path: build-aux/io.github.achetagames.epic_asset_manager.json
          run-tests: true
          cache-key: flatpak-builder-${{ github.sha }}
