name: Rust

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  release:
    release:
      types: [ published ]

env:
  CARGO_TERM_COLOR: always

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: epic_asset_manager.flatpak
          manifest-path: build-aux/io.github.achetagames.epic_asset_manager.json
          cache-key: flatpak-builder-${{ github.sha }}
