on: push
name: Find Secrets
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Self sast-scan
        uses: AppThreat/sast-scan-action@v1.0.0
        with:
          output: reports
          type: rust,bash
      - name: Upload scan reports
        uses: actions/upload-artifact@v4
        with:
          name: sast-scan-reports
          path: reports
